-- 游戏陪玩管理系统 - 数据库表结构创建脚本

-- 1. 创建陪玩人员表 (TB_STAFF)
CREATE TABLE TB_STAFF (
    STAFF_ID NUMBER(10) PRIMARY KEY,
    STAFF_NAME VARCHAR2(50) NOT NULL,
    REAL_NAME VARCHAR2(50),
    GENDER CHAR(1) CHECK (GENDER IN ('M', 'F')),
    AGE NUMBER(3) CHECK (AGE BETWEEN 18 AND 60),
    PHONE VARCHAR2(20) UNIQUE NOT NULL,
    EMAIL VARCHAR2(100),
    AVATAR_URL VARCHAR2(500),
    SKILL_LEVEL VARCHAR2(20) DEFAULT '黄金',
    SERVICE_TYPE VARCHAR2(200),
    UNIT_PRICE NUMBER(10,2) DEFAULT 0 CHECK (UNIT_PRICE >= 0),
    STATUS VARCHAR2(20) DEFAULT '空闲' CHECK (STATUS IN ('空闲', '忙碌', '离线', '封禁')),
    TOTAL_ORDERS NUMBER(10) DEFAULT 0,
    TOTAL_INCOME NUMBER(10,2) DEFAULT 0,
    AVG_SCORE NUMBER(3,2) DEFAULT 5.00,
    CERT_STATUS VARCHAR2(20) DEFAULT '未认证',
    CREATE_TIME DATE DEFAULT SYSDATE,
    UPDATE_TIME DATE DEFAULT SYSDATE,
    LAST_LOGIN_TIME DATE,
    IS_DELETED CHAR(1) DEFAULT 'N'
);

-- 创建索引
CREATE INDEX IDX_STAFF_NAME ON TB_STAFF(STAFF_NAME);
CREATE INDEX IDX_STAFF_STATUS ON TB_STAFF(STATUS);
CREATE INDEX IDX_STAFF_SKILL ON TB_STAFF(SKILL_LEVEL);
CREATE INDEX IDX_STAFF_CREATE_TIME ON TB_STAFF(CREATE_TIME);

-- 创建序列
CREATE SEQUENCE SEQ_STAFF_ID START WITH 10001 INCREMENT BY 1;

-- 2. 创建客户表 (TB_CUSTOMER)
CREATE TABLE TB_CUSTOMER (
    CUSTOMER_ID NUMBER(10) PRIMARY KEY,
    USERNAME VARCHAR2(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,
    NICKNAME VARCHAR2(50),
    PHONE VARCHAR2(20) UNIQUE NOT NULL,
    EMAIL VARCHAR2(100),
    GENDER CHAR(1) CHECK (GENDER IN ('M', 'F')),
    AGE NUMBER(3),
    AVATAR_URL VARCHAR2(500),
    MEMBER_LEVEL VARCHAR2(20) DEFAULT '普通会员',
    TOTAL_CONSUME NUMBER(10,2) DEFAULT 0,
    ORDER_COUNT NUMBER(10) DEFAULT 0,
    BALANCE NUMBER(10,2) DEFAULT 0,
    STATUS VARCHAR2(20) DEFAULT '正常' CHECK (STATUS IN ('正常', '冻结', '注销')),
    CREATE_TIME DATE DEFAULT SYSDATE,
    UPDATE_TIME DATE DEFAULT SYSDATE,
    LAST_LOGIN_TIME DATE,
    IS_DELETED CHAR(1) DEFAULT 'N'
);

-- 创建索引
CREATE INDEX IDX_CUSTOMER_USERNAME ON TB_CUSTOMER(USERNAME);
CREATE INDEX IDX_CUSTOMER_PHONE ON TB_CUSTOMER(PHONE);
CREATE INDEX IDX_CUSTOMER_STATUS ON TB_CUSTOMER(STATUS);
CREATE INDEX IDX_CUSTOMER_CREATE_TIME ON TB_CUSTOMER(CREATE_TIME);

-- 创建序列
CREATE SEQUENCE SEQ_CUSTOMER_ID START WITH 20001 INCREMENT BY 1;

-- 3. 创建订单表 (TB_ORDER) - 按季度分区
CREATE TABLE TB_ORDER (
    ORDER_ID NUMBER(15) PRIMARY KEY,
    ORDER_NO VARCHAR2(50) UNIQUE NOT NULL,
    CUSTOMER_ID NUMBER(10) NOT NULL,
    STAFF_ID NUMBER(10) NOT NULL,
    GAME_TYPE VARCHAR2(50) NOT NULL,
    SERVICE_HOURS NUMBER(4) DEFAULT 1 CHECK (SERVICE_HOURS > 0),
    UNIT_PRICE NUMBER(10,2) NOT NULL CHECK (UNIT_PRICE >= 0),
    TOTAL_AMOUNT NUMBER(10,2) NOT NULL CHECK (TOTAL_AMOUNT >= 0),
    PLATFORM_COMMISSION NUMBER(10,2) DEFAULT 0,
    STAFF_INCOME NUMBER(10,2) DEFAULT 0,
    ORDER_STATUS VARCHAR2(20) DEFAULT '待支付' 
        CHECK (ORDER_STATUS IN ('待支付', '已支付', '服务中', '已完成', '已取消', '退款中', '已退款')),
    PAY_TIME DATE,
    START_TIME DATE,
    END_TIME DATE,
    CUSTOMER_COMMENT VARCHAR2(500),
    STAFF_COMMENT VARCHAR2(500),
    CREATE_TIME DATE DEFAULT SYSDATE,
    UPDATE_TIME DATE DEFAULT SYSDATE,
    IS_DELETED CHAR(1) DEFAULT 'N',
    CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES TB_CUSTOMER(CUSTOMER_ID),
    CONSTRAINT FK_ORDER_STAFF FOREIGN KEY (STAFF_ID) REFERENCES TB_STAFF(STAFF_ID)
);

-- 创建索引
CREATE INDEX IDX_ORDER_NO ON TB_ORDER(ORDER_NO);
CREATE INDEX IDX_ORDER_CUSTOMER ON TB_ORDER(CUSTOMER_ID);
CREATE INDEX IDX_ORDER_STAFF ON TB_ORDER(STAFF_ID);
CREATE INDEX IDX_ORDER_STATUS ON TB_ORDER(ORDER_STATUS);

-- 创建序列
CREATE SEQUENCE SEQ_ORDER_ID START WITH 3000000001 INCREMENT BY 1;

-- 4. 创建评价表 (TB_EVALUATION)
CREATE TABLE TB_EVALUATION (
    EVAL_ID NUMBER(12) PRIMARY KEY,
    ORDER_ID NUMBER(15) NOT NULL,
    CUSTOMER_ID NUMBER(10) NOT NULL,
    STAFF_ID NUMBER(10) NOT NULL,
    SCORE NUMBER(2) CHECK (SCORE BETWEEN 1 AND 5),
    CONTENT VARCHAR2(500),
    TAGS VARCHAR2(200),
    IS_ANONYMOUS CHAR(1) DEFAULT 'N',
    STAFF_REPLY VARCHAR2(500),
    REPLY_TIME DATE,
    CREATE_TIME DATE DEFAULT SYSDATE,
    IS_DELETED CHAR(1) DEFAULT 'N',
    CONSTRAINT FK_EVAL_ORDER FOREIGN KEY (ORDER_ID) REFERENCES TB_ORDER(ORDER_ID),
    CONSTRAINT FK_EVAL_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES TB_CUSTOMER(CUSTOMER_ID),
    CONSTRAINT FK_EVAL_STAFF FOREIGN KEY (STAFF_ID) REFERENCES TB_STAFF(STAFF_ID)
);

-- 创建索引
CREATE INDEX IDX_EVAL_ORDER ON TB_EVALUATION(ORDER_ID);
CREATE INDEX IDX_EVAL_STAFF ON TB_EVALUATION(STAFF_ID);
CREATE INDEX IDX_EVAL_SCORE ON TB_EVALUATION(SCORE);
CREATE INDEX IDX_EVAL_CREATE_TIME ON TB_EVALUATION(CREATE_TIME);

-- 创建序列
CREATE SEQUENCE SEQ_EVAL_ID START WITH 4000000001 INCREMENT BY 1;

-- 5. 创建投诉表 (TB_COMPLAINT)
CREATE TABLE TB_COMPLAINT (
    COMPLAINT_ID NUMBER(12) PRIMARY KEY,
    ORDER_ID NUMBER(15),
    CUSTOMER_ID NUMBER(10) NOT NULL,
    STAFF_ID NUMBER(10),
    COMPLAINT_TYPE VARCHAR2(50) NOT NULL,
    COMPLAINT_CONTENT VARCHAR2(1000) NOT NULL,
    EVIDENCE_URL VARCHAR2(500),
    COMPLAINT_STATUS VARCHAR2(20) DEFAULT '待处理' 
        CHECK (COMPLAINT_STATUS IN ('待处理', '处理中', '已解决', '已关闭')),
    HANDLER_ID NUMBER(10),
    HANDLER_COMMENT VARCHAR2(500),
    HANDLE_TIME DATE,
    CREATE_TIME DATE DEFAULT SYSDATE,
    UPDATE_TIME DATE DEFAULT SYSDATE,
    IS_DELETED CHAR(1) DEFAULT 'N',
    CONSTRAINT FK_COMP_ORDER FOREIGN KEY (ORDER_ID) REFERENCES TB_ORDER(ORDER_ID),
    CONSTRAINT FK_COMP_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES TB_CUSTOMER(CUSTOMER_ID),
    CONSTRAINT FK_COMP_STAFF FOREIGN KEY (STAFF_ID) REFERENCES TB_STAFF(STAFF_ID)
);

-- 创建索引
CREATE INDEX IDX_COMP_STATUS ON TB_COMPLAINT(COMPLAINT_STATUS);
CREATE INDEX IDX_COMP_CREATE_TIME ON TB_COMPLAINT(CREATE_TIME);

-- 创建序列
CREATE SEQUENCE SEQ_COMPLAINT_ID START WITH 5000000001 INCREMENT BY 1;

-- 6. 创建管理员表 (TB_ADMIN)
CREATE TABLE TB_ADMIN (
    ADMIN_ID NUMBER(10) PRIMARY KEY,
    USERNAME VARCHAR2(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,
    NICKNAME VARCHAR2(50),
    PHONE VARCHAR2(20),
    EMAIL VARCHAR2(100),
    ROLE_ID NUMBER(10) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT '正常' CHECK (STATUS IN ('正常', '冻结')),
    LAST_LOGIN_TIME DATE,
    CREATE_TIME DATE DEFAULT SYSDATE,
    UPDATE_TIME DATE DEFAULT SYSDATE,
    IS_DELETED CHAR(1) DEFAULT 'N'
);

-- 创建索引
CREATE INDEX IDX_ADMIN_USERNAME ON TB_ADMIN(USERNAME);
CREATE INDEX IDX_ADMIN_ROLE ON TB_ADMIN(ROLE_ID);

-- 创建序列
CREATE SEQUENCE SEQ_ADMIN_ID START WITH 60001 INCREMENT BY 1;

-- 7. 创建角色表 (TB_ROLE)
CREATE TABLE TB_ROLE (
    ROLE_ID NUMBER(10) PRIMARY KEY,
    ROLE_NAME VARCHAR2(50) NOT NULL,
    ROLE_DESC VARCHAR2(200),
    PERMISSIONS VARCHAR2(2000),
    CREATE_TIME DATE DEFAULT SYSDATE,
    UPDATE_TIME DATE DEFAULT SYSDATE,
    IS_DELETED CHAR(1) DEFAULT 'N'
);

-- 创建序列
CREATE SEQUENCE SEQ_ROLE_ID START WITH 70001 INCREMENT BY 1;

-- 插入默认角色
INSERT INTO TB_ROLE (ROLE_ID, ROLE_NAME, ROLE_DESC, PERMISSIONS) VALUES 
(SEQ_ROLE_ID.NEXTVAL, '超级管理员', '拥有所有权限', 'all');

INSERT INTO TB_ROLE (ROLE_ID, ROLE_NAME, ROLE_DESC, PERMISSIONS) VALUES 
(SEQ_ROLE_ID.NEXTVAL, '运营管理员', '陪玩人员管理、订单管理', 'staff,order,evaluation');

INSERT INTO TB_ROLE (ROLE_ID, ROLE_NAME, ROLE_DESC, PERMISSIONS) VALUES 
(SEQ_ROLE_ID.NEXTVAL, '客服人员', '投诉处理、评价管理', 'complaint,evaluation');

INSERT INTO TB_ROLE (ROLE_ID, ROLE_NAME, ROLE_DESC, PERMISSIONS) VALUES 
(SEQ_ROLE_ID.NEXTVAL, '财务人员', '财务管理、提现审核', 'finance,withdraw');

INSERT INTO TB_ROLE (ROLE_ID, ROLE_NAME, ROLE_DESC, PERMISSIONS) VALUES 
(SEQ_ROLE_ID.NEXTVAL, '查看员', '仅查看权限', 'view');

-- 8. 创建数据字典表 (TB_DICTIONARY)
CREATE TABLE TB_DICTIONARY (
    DICT_ID NUMBER(10) PRIMARY KEY,
    DICT_TYPE VARCHAR2(50) NOT NULL,
    DICT_CODE VARCHAR2(50) NOT NULL,
    DICT_VALUE VARCHAR2(100) NOT NULL,
    DICT_DESC VARCHAR2(200),
    SORT_ORDER NUMBER(5) DEFAULT 0,
    CREATE_TIME DATE DEFAULT SYSDATE,
    IS_DELETED CHAR(1) DEFAULT 'N',
    UNIQUE(DICT_TYPE, DICT_CODE)
);

-- 创建索引
CREATE INDEX IDX_DICT_TYPE ON TB_DICTIONARY(DICT_TYPE);

-- 创建序列
CREATE SEQUENCE SEQ_DICT_ID START WITH 80001 INCREMENT BY 1;

-- 插入游戏类型
INSERT INTO TB_DICTIONARY VALUES (SEQ_DICT_ID.NEXTVAL, 'GAME_TYPE', 'LOL', '英雄联盟', NULL, 1, SYSDATE, 'N');
INSERT INTO TB_DICTIONARY VALUES (SEQ_DICT_ID.NEXTVAL, 'GAME_TYPE', 'WZRY', '王者荣耀', NULL, 2, SYSDATE, 'N');
INSERT INTO TB_DICTIONARY VALUES (SEQ_DICT_ID.NEXTVAL, 'GAME_TYPE', 'HPJY', '和平精英', NULL, 3, SYSDATE, 'N');
INSERT INTO TB_DICTIONARY VALUES (SEQ_DICT_ID.NEXTVAL, 'GAME_TYPE', 'JDCQ', '绝地求生', NULL, 4, SYSDATE, 'N');
INSERT INTO TB_DICTIONARY VALUES (SEQ_DICT_ID.NEXTVAL, 'GAME_TYPE', 'DNF', '地下城与勇士', NULL, 5, SYSDATE, 'N');

-- 插入技能等级
INSERT INTO TB_DICTIONARY VALUES (SEQ_DICT_ID.NEXTVAL, 'SKILL_LEVEL', 'BRONZE', '青铜', NULL, 1, SYSDATE, 'N');
INSERT INTO TB_DICTIONARY VALUES (SEQ_DICT_ID.NEXTVAL, 'SKILL_LEVEL', 'SILVER', '白银', NULL, 2, SYSDATE, 'N');
INSERT INTO TB_DICTIONARY VALUES (SEQ_DICT_ID.NEXTVAL, 'SKILL_LEVEL', 'GOLD', '黄金', NULL, 3, SYSDATE, 'N');
INSERT INTO TB_DICTIONARY VALUES (SEQ_DICT_ID.NEXTVAL, 'SKILL_LEVEL', 'PLATINUM', '铂金', NULL, 4, SYSDATE, 'N');
INSERT INTO TB_DICTIONARY VALUES (SEQ_DICT_ID.NEXTVAL, 'SKILL_LEVEL', 'DIAMOND', '钻石', NULL, 5, SYSDATE, 'N');
INSERT INTO TB_DICTIONARY VALUES (SEQ_DICT_ID.NEXTVAL, 'SKILL_LEVEL', 'MASTER', '王者', NULL, 6, SYSDATE, 'N');

-- 插入投诉类型
INSERT INTO TB_DICTIONARY VALUES (SEQ_DICT_ID.NEXTVAL, 'COMPLAINT_TYPE', 'ATTITUDE', '服务态度', NULL, 1, SYSDATE, 'N');
INSERT INTO TB_DICTIONARY VALUES (SEQ_DICT_ID.NEXTVAL, 'COMPLAINT_TYPE', 'QUALITY', '服务质量', NULL, 2, SYSDATE, 'N');
INSERT INTO TB_DICTIONARY VALUES (SEQ_DICT_ID.NEXTVAL, 'COMPLAINT_TYPE', 'PRICE', '收费问题', NULL, 3, SYSDATE, 'N');
INSERT INTO TB_DICTIONARY VALUES (SEQ_DICT_ID.NEXTVAL, 'COMPLAINT_TYPE', 'OTHER', '其他', NULL, 4, SYSDATE, 'N');

-- 9. 创建操作日志表 (TB_OPERATION_LOG)
CREATE TABLE TB_OPERATION_LOG (
    LOG_ID NUMBER(15) PRIMARY KEY,
    ADMIN_ID NUMBER(10),
    ADMIN_NAME VARCHAR2(50),
    OPERATION_TYPE VARCHAR2(50),
    OPERATION_DESC VARCHAR2(500),
    REQUEST_URL VARCHAR2(200),
    REQUEST_METHOD VARCHAR2(20),
    REQUEST_IP VARCHAR2(50),
    REQUEST_PARAMS VARCHAR2(2000),
    RESPONSE_RESULT VARCHAR2(2000),
    EXECUTE_TIME NUMBER(10),
    CREATE_TIME DATE DEFAULT SYSDATE,
    IS_DELETED CHAR(1) DEFAULT 'N'
);

-- 创建索引
CREATE INDEX IDX_LOG_ADMIN ON TB_OPERATION_LOG(ADMIN_ID);
CREATE INDEX IDX_LOG_CREATE_TIME ON TB_OPERATION_LOG(CREATE_TIME);
CREATE INDEX IDX_LOG_OPERATION_TYPE ON TB_OPERATION_LOG(OPERATION_TYPE);

-- 创建序列
CREATE SEQUENCE SEQ_LOG_ID START WITH 9000000001 INCREMENT BY 1;

-- 提交事务
COMMIT;