-- 创建提现表 (TB_WITHDRAW)
CREATE TABLE TB_WITHDRAW (
    WITHDRAW_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    STAFF_ID INT NOT NULL,
    AMOUNT DECIMAL(10,2) NOT NULL,
    STATUS VARCHAR(20) DEFAULT '待审核' CHECK (STATUS IN ('待审核', '处理中', '已通过', '已拒绝')),
    REMARK VARCHAR(200),
    APPLY_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    APPROVE_TIME DATETIME,
    APPROVER VARCHAR(50),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IS_DELETED CHAR(1) DEFAULT 'N',
    FOREIGN KEY (STAFF_ID) REFERENCES TB_STAFF(STAFF_ID)
);

-- 创建索引
CREATE INDEX IDX_WITHDRAW_STAFF ON TB_WITHDRAW(STAFF_ID);
CREATE INDEX IDX_WITHDRAW_STATUS ON TB_WITHDRAW(STATUS);
CREATE INDEX IDX_WITHDRAW_APPLY_TIME ON TB_WITHDRAW(APPLY_TIME);