-- 更新陪玩人员的订单数和收入（基于订单数据）
DECLARE
  order_table_exists NUMBER := 0;
  staff_table_exists NUMBER := 0;
  customer_table_exists NUMBER := 0;
BEGIN
  -- 检查表是否存在
  SELECT COUNT(*) INTO order_table_exists FROM USER_TABLES WHERE TABLE_NAME = 'TB_ORDER';
  SELECT COUNT(*) INTO staff_table_exists FROM USER_TABLES WHERE TABLE_NAME = 'TB_STAFF';
  SELECT COUNT(*) INTO customer_table_exists FROM USER_TABLES WHERE TABLE_NAME = 'TB_CUSTOMER';
  
  IF order_table_exists > 0 AND staff_table_exists > 0 THEN
    -- 更新陪玩人员的订单数和收入（基于订单数据）
    UPDATE TB_STAFF SET 
      TOTAL_ORDERS = (
        SELECT COUNT(*) 
        FROM TB_ORDER 
        WHERE TB_ORDER.STAFF_ID = TB_STAFF.STAFF_ID 
        AND TB_ORDER.ORDER_STATUS = '已完成'
      ),
      TOTAL_INCOME = (
        SELECT COALESCE(SUM(TOTAL_AMOUNT), 0) 
        FROM TB_ORDER 
        WHERE TB_ORDER.STAFF_ID = TB_STAFF.STAFF_ID 
        AND TB_ORDER.ORDER_STATUS = '已完成'
      );
  ELSE
    DBMS_OUTPUT.PUT_LINE('表 TB_ORDER 或 TB_STAFF 不存在');
  END IF;
  
  IF order_table_exists > 0 AND customer_table_exists > 0 THEN
    -- 更新客户的订单数和消费金额（基于订单数据）
    UPDATE TB_CUSTOMER SET 
      ORDER_COUNT = (
        SELECT COUNT(*) 
        FROM TB_ORDER 
        WHERE TB_ORDER.CUSTOMER_ID = TB_CUSTOMER.CUSTOMER_ID
      ),
      TOTAL_CONSUME = (
        SELECT COALESCE(SUM(TOTAL_AMOUNT), 0) 
        FROM TB_ORDER 
        WHERE TB_ORDER.CUSTOMER_ID = TB_CUSTOMER.CUSTOMER_ID
      );
  ELSE
    DBMS_OUTPUT.PUT_LINE('表 TB_ORDER 或 TB_CUSTOMER 不存在');
  END IF;

  COMMIT;

  -- 显示各表数据统计（如果表存在）
  IF (SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = 'TB_STAFF') > 0 THEN
    FOR rec IN (SELECT 'TB_STAFF' AS TABLE_NAME, COUNT(*) AS COUNT FROM TB_STAFF) LOOP
      DBMS_OUTPUT.PUT_LINE(rec.TABLE_NAME || ': ' || rec.COUNT);
    END LOOP;
  END IF;
  
  IF (SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = 'TB_CUSTOMER') > 0 THEN
    FOR rec IN (SELECT 'TB_CUSTOMER' AS TABLE_NAME, COUNT(*) AS COUNT FROM TB_CUSTOMER) LOOP
      DBMS_OUTPUT.PUT_LINE(rec.TABLE_NAME || ': ' || rec.COUNT);
    END LOOP;
  END IF;
  
  IF (SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = 'TB_ORDER') > 0 THEN
    FOR rec IN (SELECT 'TB_ORDER' AS TABLE_NAME, COUNT(*) AS COUNT FROM TB_ORDER) LOOP
      DBMS_OUTPUT.PUT_LINE(rec.TABLE_NAME || ': ' || rec.COUNT);
    END LOOP;
  END IF;
  
  IF (SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = 'TB_EVALUATION') > 0 THEN
    FOR rec IN (SELECT 'TB_EVALUATION' AS TABLE_NAME, COUNT(*) AS COUNT FROM TB_EVALUATION) LOOP
      DBMS_OUTPUT.PUT_LINE(rec.TABLE_NAME || ': ' || rec.COUNT);
    END LOOP;
  END IF;
  
  IF (SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = 'TB_COMPLAINT') > 0 THEN
    FOR rec IN (SELECT 'TB_COMPLAINT' AS TABLE_NAME, COUNT(*) AS COUNT FROM TB_COMPLAINT) LOOP
      DBMS_OUTPUT.PUT_LINE(rec.TABLE_NAME || ': ' || rec.COUNT);
    END LOOP;
  END IF;
END;
/